### ISSUE TITLE
intraday.props and strategy directory

### ISSUE THREAD

**Issue by vinceyap88** [rterp/SumZeroTrading#22]
Hi,
    I would like to test out your API but could not find the properties files(e.g. intraday.props...) in your repository. Would you mind attach it here? 
    Besides, I have noticed it is required to set the StrategyDirectory. How is the format of the strategy file stored in this directory?
   
   Many thanks.
Best Regards,
Vincent Yap

**Comment by rterp** [comment]
Sorry about that @vinceyap88 .  I've uploaded each strategy's prop file into their project's resources directory.  You find find the intraday prop file at:
https://github.com/rterp/SumZeroTrading/tree/master/examples/IntradayTradingExample/src/main/resources

**Comment by vinceyap88** [comment]
Thank you. :)

**Comment by rterp** [comment]
Let me know if you have any other questions, the API is very much a work in progress.
