### ISSUE TITLE
Undefined Java Methods Found in Example Project

### ISSUE THREAD

**Issue by vinceyap88** [rterp/SumZeroTrading#23]
Hi,
    I have found that the example projects EODTradingStrategy and IntradayTradingExample contains the undefined java methods(attached).

   If you have the latest copies of these projects, kindly upload to the repositories.

Cheer,
Vincent Yap
<img width="1002" alt="screen shot 2016-06-20 at 3 10 11 pm" src="https://cloud.githubusercontent.com/assets/12798134/16190963/7b6edd32-3714-11e6-8f32-c0d2b9f0bf04.png">

**Comment by rterp** [comment]
The project is using a library called "lombok", which will automatically generate getter/setter methods when the project is compiled .  You'll see a number of variables at the top of the TradeReferenceLine class annotated with @Getter.  Try to do a clean/build from Netbeans and see if this takes care of the issue.

**Comment by vinceyap88** [comment]
Thank you. I will try it in Eclipse.
