### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by asaen** [rterp/SumZeroTrading#46]
Running `mvn clean install` leads to the error:
```
[ERROR] Failed to execute goal on project collective2-broker-api-impl: Could not resolve dependencies for project com.sumzerotrading:collective2-broker-api-impl:jar:1.0.0-SNAPSHOT: Could not find artifact com.sumzerotrading:J4C2:jar:1.0.0-SNAPSHOT -> [Help 1]
```

**Comment by rterp** [comment]
There's a dependency on the J4C2 library.  I'll need to get a release build of the library uploaded to maven central and then the collective2-broker-api-impl project should build.

**Comment by rterp** [comment]
I've uploaded J4C2 to bintray, so the SumZero API will now build correctly.
